spring:
  application:
    name: docuchat
  datasource:
    url: jdbc:postgresql://localhost:5433/docuchat
    username: docuchat
    password: ${POSTGRES_PASSWORD}
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.0-flash
        embedding:
          api-key: ${GEMINI_API_KEY}
          text:
            options:
              model: gemini-embedding-001
  vectorstore:
    pgvector:
      initialize-schema: true
      dimensions: 3072